"""Initial migration.

Revision ID: 702613cb81a8
Revises: 
Create Date: 2025-02-24 00:41:14.332236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702613cb81a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specific_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('original_appointment_date', sa.Date(), nullable=True),
    sa.Column('original_position', sa.String(length=100), nullable=True),
    sa.Column('original_salary_grade', sa.String(length=50), nullable=True),
    sa.Column('original_salary_step', sa.String(length=50), nullable=True),
    sa.Column('original_monthly_salary', sa.Float(), nullable=True),
    sa.Column('current_appointment_date', sa.Date(), nullable=True),
    sa.Column('current_position', sa.String(length=100), nullable=True),
    sa.Column('current_salary_grade', sa.String(length=50), nullable=True),
    sa.Column('current_salary_step', sa.String(length=50), nullable=True),
    sa.Column('current_monthly_salary', sa.Float(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('school')
    op.drop_table('specific_model')
    op.drop_table('district')
    # ### end Alembic commands ###
